[package]
name = "deterministic-finite-automaton"
version = "0.1.0"
edition = "2021"
description = "Simple generic implementation of a deterministic finite automaton"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
